name: "Deploy Storybook"
description: "Deploy Storybook to Netlify"

inputs:
  production:
    description: "Is production"
    required: false
    default: "false"

outputs:
  preview_url:
    description: "Netlify Preview URL"
    value: ${{ steps.deploy_to_netlify.outputs.preview_url }}
  live_url:
    description: "Netlify Live URL"
    value: ${{ steps.deploy_to_netlify.outputs.live_url }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
    - uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.24.1
        run_install: |
          - args: [--frozen-lockfile]
    - run: pnpm run storybook:build
    - id: deploy_to_netlify
      shell: bash
      run: |
        DEPLOY_COMMAND="netlify deploy -d storybook-static --json --prod"

        RESULT=$(pnpx $DEPLOY_COMMAND)

        echo "::set-output name=preview_url::$(echo $RESULT | jq -r .deploy_url)"
        echo "::set-output name=live_url::$(echo $RESULT | jq -r .url)"
