name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - synchronize

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.1
          run_install: |
            - args: [--frozen-lockfile]
      - run: pnpm run storybook:build
      - id: deploy-to-netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          result = $(
            pnpx netlify deploy \
            -d storybook-static \
            --auth $NETLIFY_AUTH_TOKEN \
            --json \
            $([ $GITHUB_EVENT_NAME = "push" ] && echo --prod)
          )
          echo "::set-output preview_url::$(echo $result | jq -r .preview_url)"
      - if: ${{ github.event_name == 'pull_request' && success() }}
        uses: actions/github-script@v5
        env:
          PREVIEW_URL: ${{ steps.deploy-to-netlify.outputs.deploy_url }}
        with:
          script: |
            const { PREVIEW_URL } = process.env
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${ PREVIEW_URL }`
            })
