name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - synchronize

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.1
          run_install: |
            - args: [--frozen-lockfile]
      - run: pnpm run storybook:build
      - name: Deploy to Netlify
        id: deploy_to_netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.STORYBOOK_NETLIFY_AUTH_TOKEN }}
        run: |
          DEPLOY_COMMAND="netlify deploy -d storybook-static --auth ${{ env.NETLIFY_AUTH_TOKEN }} --json"
          [ "$GITHUB_EVENT_NAME" = "push" ] && DEPLOY_COMMAND+=" --prod"

          RESULT=$(pnpx $DEPLOY_COMMAND)

          echo $DEPLOY_COMMAND
          echo $RESULT
      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' && success() }}
        env:
          PREVIEW_URL: ${{ steps.deploy_to_netlify.outputs.PREVIEW_URL }}
        uses: actions/github-script@v5
        with:
          script: |
            const { PREVIEW_URL } = process.env
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Storybook Preview \n ${PREVIEW_URL}`
            })
